export enum EnumTypeMessage {
  LOGIN_ERROR = 'LOGIN_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  CREATE_SUCCESS = 'CREATE_SUCCESS',
  EDIT_SUCCESS =  'EDIT_SUCCESS',
  DELETE_SUCCESS = 'DELETE_SUCCESS',
  OPERATION_ERROR = 'OPERATION_ERROR'
}